# Generated by Django 3.0 on 2020-01-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='Mob',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
