# Generated by Django 3.0 on 2020-01-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0002_sign_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('Fid', models.IntegerField(primary_key='True', serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Qualification', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('BatchInCharge', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='Mob',
            new_name='Mobile',
        ),
    ]
