# Generated by Django 3.0 on 2020-01-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0003_auto_20200102_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='UserName',
            new_name='username',
        ),
    ]
