# Generated by Django 3.0 on 2020-01-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0004_auto_20200102_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='Password',
            new_name='password',
        ),
    ]
