# Generated by Django 3.0 on 2020-01-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0005_auto_20200102_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('Sid', models.IntegerField(primary_key='True', serialize=False)),
                ('AdmNo', models.IntegerField()),
                ('AdmDate', models.DateField()),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=40)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('Guardian', models.CharField(max_length=20)),
                ('Batch', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
