# Generated by Django 3.0 on 2020-01-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0007_fac_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('status_h1', models.CharField(max_length=20)),
                ('status_h2', models.CharField(max_length=20)),
                ('status_h3', models.CharField(max_length=20)),
                ('status_h4', models.CharField(max_length=20)),
                ('Sid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssessmentNo', models.IntegerField()),
                ('Sub1', models.IntegerField()),
                ('Sub2', models.IntegerField()),
                ('Sub3', models.IntegerField()),
                ('Percentage', models.FloatField()),
                ('Sid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attapp.student')),
            ],
        ),
    ]
