# Generated by Django 3.0 on 2020-01-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0009_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='AdmNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
