# Generated by Django 3.0 on 2020-01-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0010_auto_20200103_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='AdmDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
