# Generated by Django 3.0 on 2020-01-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0011_auto_20200103_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
