# Generated by Django 3.0 on 2020-01-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0012_auto_20200103_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
