# Generated by Django 3.0 on 2020-01-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0013_auto_20200103_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
