# Generated by Django 3.0 on 2020-01-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0016_auto_20200103_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='Sid',
            field=models.IntegerField(),
        ),
    ]
