# Generated by Django 3.0 on 2020-01-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0017_auto_20200106_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='AssessmentNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='Percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='Sub1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='Sub2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='Sub3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
