# Generated by Django 3.0 on 2020-01-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0018_auto_20200106_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='leavefac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.IntegerField()),
                ('Fromdate', models.DateField()),
                ('Todate', models.DateField()),
                ('Reason', models.CharField(max_length=40)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='leavestu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sid', models.IntegerField()),
                ('Fromdate', models.DateField()),
                ('Todate', models.DateField()),
                ('Reason', models.CharField(max_length=40)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='fac_attendance',
            name='Fid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stud_attendance',
            name='Sid',
            field=models.IntegerField(),
        ),
    ]
