# Generated by Django 3.0 on 2020-01-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0020_stud_attendance_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=10)),
                ('Batch', models.CharField(max_length=10)),
                ('Hour1', models.CharField(max_length=10)),
                ('Hour2', models.CharField(max_length=10)),
                ('Hour3', models.CharField(max_length=10)),
                ('Hour4', models.CharField(max_length=10)),
            ],
        ),
    ]
